-- 샵플로우 핵심 구매·판매 흐름 스키마 (PostgreSQL 참조 DDL)
-- 이 파일은 diagrams/schema.dbml에서 docs/diagrams/generate-sql.ps1로 만든다. 직접 고치지 않는다.
-- 설계 단계의 참조용이며 마이그레이션이 아니다. 실제 변경은 플라이웨이 마이그레이션으로 한다.
-- 컨텍스트 사이 참조는 식별자 값만 저장하며 외래키가 없다(ADR-0007).
CREATE TYPE "account_type" AS ENUM (
  'customer',
  'seller',
  'admin'
);

CREATE TYPE "business_type" AS ENUM (
  'sole_proprietor',
  'corporation'
);

CREATE TYPE "seller_status" AS ENUM (
  'applied',
  'approved',
  'rejected',
  'suspended'
);

CREATE TYPE "product_status" AS ENUM (
  'on_sale',
  'suspended'
);

CREATE TYPE "order_status" AS ENUM (
  'pending_payment',
  'confirmed',
  'cancelled',
  'needs_review'
);

CREATE TYPE "sub_order_status" AS ENUM (
  'before_shipping',
  'shipping',
  'delivered',
  'purchase_confirmed',
  'cancelled'
);

CREATE TYPE "reservation_status" AS ENUM (
  'held',
  'confirmed',
  'released'
);

CREATE TYPE "payment_method" AS ENUM (
  'immediate',
  'deposit_wait'
);

CREATE TYPE "payment_status" AS ENUM (
  'ready',
  'approval_wait',
  'deposit_wait',
  'succeeded',
  'failed',
  'expired'
);

CREATE TYPE "transaction_type" AS ENUM (
  'approval',
  'refund'
);

CREATE TYPE "idempotency_status" AS ENUM (
  'processing',
  'completed'
);

CREATE TABLE "account" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "public_id" varchar(36) UNIQUE NOT NULL,
  "type" account_type NOT NULL,
  "email" varchar(255) NOT NULL,
  "password_hash" varchar(255) NOT NULL,
  "status" varchar(20) NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL
);

CREATE TABLE "seller_profile" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "account_id" bigint UNIQUE NOT NULL,
  "business_type" business_type NOT NULL,
  "business_name" varchar(100) NOT NULL,
  "business_registration_no" varchar(20) UNIQUE NOT NULL,
  "representative_name" varchar(50) NOT NULL,
  "phone" varchar(30) NOT NULL,
  "business_address" varchar(255) NOT NULL,
  "mail_order_report_no" varchar(50) NOT NULL,
  "corporate_name" varchar(100),
  "corporate_registration_no" varchar(20),
  "status" seller_status NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  CONSTRAINT "ck_seller_corporate_fields" CHECK ((business_type = 'corporation' AND corporate_name IS NOT NULL AND corporate_registration_no IS NOT NULL) OR (business_type = 'sole_proprietor' AND corporate_name IS NULL AND corporate_registration_no IS NULL))
);

CREATE TABLE "seller_document" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "seller_profile_id" bigint NOT NULL,
  "document_type" varchar(30) NOT NULL,
  "file_path" varchar(500) NOT NULL,
  "submitted_at" timestamptz NOT NULL
);

CREATE TABLE "product" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "public_id" varchar(36) UNIQUE NOT NULL,
  "seller_id" bigint NOT NULL,
  "name" varchar(200) NOT NULL,
  "description" text,
  "status" product_status NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL
);

CREATE TABLE "product_photo" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" bigint NOT NULL,
  "file_path" varchar(500) NOT NULL,
  "sort_order" int NOT NULL
);

CREATE TABLE "product_variant" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" bigint NOT NULL,
  "option_values" jsonb NOT NULL,
  "price" bigint NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  CONSTRAINT "ck_variant_price_positive" CHECK (price > 0)
);

CREATE TABLE "stock" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "variant_id" bigint UNIQUE NOT NULL,
  "available_qty" bigint NOT NULL,
  "updated_at" timestamptz NOT NULL,
  CONSTRAINT "ck_stock_non_negative" CHECK (available_qty >= 0)
);

CREATE TABLE "stock_reservation" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "stock_id" bigint NOT NULL,
  "order_id" bigint NOT NULL,
  "variant_id" bigint NOT NULL,
  "quantity" int NOT NULL,
  "expires_at" timestamptz NOT NULL,
  "status" reservation_status NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  CONSTRAINT "ck_reservation_quantity_positive" CHECK (quantity > 0)
);

CREATE TABLE "cart_item" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "customer_id" bigint NOT NULL,
  "variant_id" bigint NOT NULL,
  "quantity" int NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  CONSTRAINT "ck_cart_quantity_positive" CHECK (quantity >= 1)
);

CREATE TABLE "customer_order" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "public_id" varchar(36) UNIQUE NOT NULL,
  "customer_id" bigint NOT NULL,
  "total_amount" bigint NOT NULL,
  "status" order_status NOT NULL,
  "shipping_recipient" varchar(50) NOT NULL,
  "shipping_phone" varchar(30) NOT NULL,
  "shipping_address" varchar(255) NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL
);

CREATE TABLE "sub_order" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "public_id" varchar(36) UNIQUE NOT NULL,
  "order_id" bigint NOT NULL,
  "seller_id" bigint NOT NULL,
  "amount" bigint NOT NULL,
  "status" sub_order_status NOT NULL,
  "purchase_confirmed_at" timestamptz,
  "cancelled_at" timestamptz,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL
);

CREATE TABLE "sub_order_item" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sub_order_id" bigint NOT NULL,
  "variant_id" bigint NOT NULL,
  "quantity" int NOT NULL,
  "unit_price" bigint NOT NULL,
  CONSTRAINT "ck_sub_order_item_quantity_positive" CHECK (quantity >= 1)
);

CREATE TABLE "delivery" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sub_order_id" bigint UNIQUE NOT NULL,
  "carrier" varchar(50) NOT NULL,
  "tracking_no" varchar(50) NOT NULL,
  "delivered_at" timestamptz,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL
);

CREATE TABLE "payment" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "public_id" varchar(36) UNIQUE NOT NULL,
  "order_id" bigint NOT NULL,
  "method" payment_method NOT NULL,
  "amount" bigint NOT NULL,
  "status" payment_status NOT NULL,
  "gateway_payment_key" varchar(100),
  "deposit_deadline" timestamptz,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL
);

CREATE TABLE "payment_transaction" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "payment_id" bigint NOT NULL,
  "type" transaction_type NOT NULL,
  "sub_order_id" bigint,
  "amount" bigint NOT NULL,
  "gateway_transaction_key" varchar(100),
  "occurred_at" timestamptz NOT NULL
);

CREATE TABLE "idempotency_key" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "scope" varchar(30) NOT NULL,
  "idem_key" varchar(100) NOT NULL,
  "request_hash" varchar(64) NOT NULL,
  "status" idempotency_status NOT NULL,
  "result" jsonb,
  "expires_at" timestamptz NOT NULL,
  "created_at" timestamptz NOT NULL
);

CREATE TABLE "audit_log" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "target_type" varchar(30) NOT NULL,
  "target_id" bigint NOT NULL,
  "from_status" varchar(30),
  "to_status" varchar(30) NOT NULL,
  "actor" varchar(100) NOT NULL,
  "occurred_at" timestamptz NOT NULL
);

CREATE UNIQUE INDEX "uq_account_type_email" ON "account" ("type", "email");

CREATE INDEX ON "product" ("seller_id");

CREATE INDEX ON "product" ("status", "name");

CREATE UNIQUE INDEX "uq_variant_product_options" ON "product_variant" ("product_id", "option_values");

CREATE INDEX "ix_reservation_expiry" ON "stock_reservation" ("status", "expires_at");

CREATE INDEX ON "stock_reservation" ("order_id");

CREATE UNIQUE INDEX "uq_cart_customer_variant" ON "cart_item" ("customer_id", "variant_id");

CREATE INDEX ON "customer_order" ("customer_id", "created_at");

CREATE INDEX ON "sub_order" ("seller_id", "status");

CREATE INDEX ON "sub_order" ("status", "updated_at");

CREATE INDEX ON "payment" ("order_id");

CREATE UNIQUE INDEX ON "payment" ("gateway_payment_key");

CREATE INDEX ON "payment" ("status", "deposit_deadline");

CREATE INDEX ON "payment_transaction" ("sub_order_id", "type");

CREATE UNIQUE INDEX "uq_idempotency_scope_key" ON "idempotency_key" ("scope", "idem_key");

CREATE INDEX ON "idempotency_key" ("expires_at");

CREATE INDEX ON "audit_log" ("target_type", "target_id");

COMMENT ON TABLE "account" IS '고객, 판매자, 운영자 계정. 계정 유형별로 이메일이 유일하다.';

COMMENT ON COLUMN "account"."public_id" IS '화면과 외부에 노출하는 식별자';

COMMENT ON COLUMN "account"."password_hash" IS '솔트가 적용된 해시만 저장';

COMMENT ON TABLE "seller_profile" IS '판매자 정보. 법인사업자는 corporate_name과 corporate_registration_no가 필수, 개인사업자는 비어 있어야 한다(검사 제약).';

COMMENT ON COLUMN "seller_profile"."business_name" IS '상호명';

COMMENT ON COLUMN "seller_profile"."business_registration_no" IS '사업자등록번호, 유일';

COMMENT ON COLUMN "seller_profile"."representative_name" IS '대표자명 (대표자 주민등록번호는 저장하지 않는다)';

COMMENT ON COLUMN "seller_profile"."mail_order_report_no" IS '통신판매업 신고번호';

COMMENT ON COLUMN "seller_profile"."corporate_name" IS '법인사업자만. 개인사업자는 null';

COMMENT ON COLUMN "seller_profile"."corporate_registration_no" IS '법인사업자만. 개인사업자는 null';

COMMENT ON TABLE "seller_document" IS '입점 서류. 판매자 본인과 운영자만 조회할 수 있다.';

COMMENT ON COLUMN "seller_document"."document_type" IS '사업자등록증 사본 등';

COMMENT ON COLUMN "seller_document"."file_path" IS '서버가 정한 이름으로 비공개 위치에 저장';

COMMENT ON TABLE "product" IS '판매자가 등록한 상품. 하나 이상의 판매 단위를 가진다.';

COMMENT ON COLUMN "product"."seller_id" IS '식별자 참조: 계정 컨텍스트의 seller_profile.id (외래키 아님)';

COMMENT ON TABLE "product_variant" IS '판매 단위(옵션 조합). 고객이 실제로 고르고 사는 단위.';

COMMENT ON COLUMN "product_variant"."option_values" IS '옵션 조합. 예: {"색상":"빨강","사이즈":"M"}. 옵션이 없으면 빈 객체';

COMMENT ON COLUMN "product_variant"."price" IS '원 단위. 0보다 커야 한다(검사 제약). 재고 수량은 stock이 소유한다';

COMMENT ON TABLE "stock" IS '판매 단위별 가용 재고. 판매 단위마다 한 행이다.';

COMMENT ON COLUMN "stock"."variant_id" IS '식별자 참조: 상품 컨텍스트의 product_variant.id (외래키 아님)';

COMMENT ON COLUMN "stock"."available_qty" IS '가용 수량. 0 이상이며 검사 제약으로 음수를 막는다. 조건부 갱신으로만 바꾼다';

COMMENT ON TABLE "stock_reservation" IS '재고 확보(선점). held 상태의 수량은 이미 stock에서 차감되어 있다. 반환은 status가 held일 때만 한 번 일어난다.';

COMMENT ON COLUMN "stock_reservation"."order_id" IS '식별자 참조: 주문 컨텍스트의 customer_order.id (외래키 아님)';

COMMENT ON COLUMN "stock_reservation"."variant_id" IS '식별자 참조: 상품 컨텍스트의 product_variant.id (외래키 아님)';

COMMENT ON COLUMN "stock_reservation"."expires_at" IS '결제 방식별 설정값(즉시 결제 15분, 입금 대기 24시간)';

COMMENT ON COLUMN "cart_item"."customer_id" IS '식별자 참조: 계정 컨텍스트의 account.id (외래키 아님)';

COMMENT ON COLUMN "cart_item"."variant_id" IS '식별자 참조: 상품 컨텍스트의 product_variant.id (외래키 아님)';

COMMENT ON COLUMN "cart_item"."quantity" IS '1 이상';

COMMENT ON TABLE "customer_order" IS '고객이 한 번에 결제한 전체 구매.';

COMMENT ON COLUMN "customer_order"."customer_id" IS '식별자 참조: 계정 컨텍스트의 account.id (외래키 아님)';

COMMENT ON COLUMN "customer_order"."total_amount" IS '하위 주문 금액의 합과 같다';

COMMENT ON TABLE "sub_order" IS '판매자별 하위 주문. 배송, 취소, 구매 확정, 이후 정산과 환불의 단위.';

COMMENT ON COLUMN "sub_order"."seller_id" IS '식별자 참조: 계정 컨텍스트의 seller_profile.id (외래키 아님)';

COMMENT ON COLUMN "sub_order"."status" IS '상태 변경은 WHERE status = 현재 상태 조건부 갱신으로만 한다. 취소와 발송이 동시에 오면 먼저 처리된 요청만 반영';

COMMENT ON COLUMN "sub_order_item"."variant_id" IS '식별자 참조: 상품 컨텍스트의 product_variant.id (외래키 아님)';

COMMENT ON COLUMN "sub_order_item"."unit_price" IS '주문 당시 단가. 이후 가격이 바뀌어도 달라지지 않는다';

COMMENT ON TABLE "delivery" IS '배송 정보. 송장 입력과 하위 주문의 상태 변경(발송 전에서 배송 중)은 같은 트랜잭션에서 처리하고, 이미 취소된 하위 주문이면 저장하지 않는다.';

COMMENT ON COLUMN "delivery"."sub_order_id" IS '식별자 참조: 주문 컨텍스트의 sub_order.id (외래키 아님). 하위 주문마다 최대 하나';

COMMENT ON COLUMN "delivery"."carrier" IS '택배사';

COMMENT ON COLUMN "delivery"."tracking_no" IS '송장 번호';

COMMENT ON COLUMN "delivery"."delivered_at" IS '판매자가 배송 완료 처리를 할 때 기록';

COMMENT ON TABLE "payment" IS '결제. 한 주문에 성공(succeeded) 결제는 하나만 있어야 한다(order_id에 대한 부분 유일 인덱스: WHERE status = succeeded).';

COMMENT ON COLUMN "payment"."order_id" IS '식별자 참조: 주문 컨텍스트의 customer_order.id (외래키 아님)';

COMMENT ON COLUMN "payment"."amount" IS '주문 총액과 같아야 한다';

COMMENT ON COLUMN "payment"."gateway_payment_key" IS '대행사 결제 키';

COMMENT ON COLUMN "payment"."deposit_deadline" IS '입금 대기 방식일 때만';

COMMENT ON TABLE "payment_transaction" IS '추가 전용. 수정과 삭제를 하지 않고 환불은 새 행을 추가한다. 하위 주문별 환불 합계는 그 하위 주문 금액을 넘을 수 없다.';

COMMENT ON COLUMN "payment_transaction"."sub_order_id" IS '식별자 참조: 주문 컨텍스트의 sub_order.id (외래키 아님). 환불일 때 대상';

COMMENT ON TABLE "idempotency_key" IS '중복 방지. (범위, 키)가 유일하다. 오래된 키는 정리 작업이 지운다.';

COMMENT ON COLUMN "idempotency_key"."scope" IS '결제 시작, 결제 승인, 취소, 웹훅';

COMMENT ON COLUMN "idempotency_key"."idem_key" IS '웹훅은 대행사 이벤트 식별자를 쓴다';

COMMENT ON COLUMN "idempotency_key"."request_hash" IS '요청 내용 해시. 같은 키에 다른 내용이면 거절';

COMMENT ON COLUMN "idempotency_key"."result" IS '저장된 처리 결과';

COMMENT ON TABLE "audit_log" IS '변경 이력. 추가만 하고 수정과 삭제를 하지 않는다. 개인정보와 카드 정보는 담지 않는다.';

COMMENT ON COLUMN "audit_log"."target_type" IS '결제, 주문, 하위 주문, 재고 확보';

COMMENT ON COLUMN "audit_log"."target_id" IS '식별자 참조(대상 종류에 따라 다름, 외래키 아님)';

COMMENT ON COLUMN "audit_log"."actor" IS '행위자(계정 식별자 또는 시스템)';

ALTER TABLE "seller_profile" ADD FOREIGN KEY ("account_id") REFERENCES "account" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "seller_document" ADD FOREIGN KEY ("seller_profile_id") REFERENCES "seller_profile" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "product_photo" ADD FOREIGN KEY ("product_id") REFERENCES "product" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "product_variant" ADD FOREIGN KEY ("product_id") REFERENCES "product" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "stock_reservation" ADD FOREIGN KEY ("stock_id") REFERENCES "stock" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sub_order" ADD FOREIGN KEY ("order_id") REFERENCES "customer_order" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sub_order_item" ADD FOREIGN KEY ("sub_order_id") REFERENCES "sub_order" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "payment_transaction" ADD FOREIGN KEY ("payment_id") REFERENCES "payment" ("id") DEFERRABLE INITIALLY IMMEDIATE;

-- ───────── DBML로 표현할 수 없는 제약 ─────────

-- 한 주문에 성공(succeeded) 결제는 하나만 있어야 한다.
CREATE UNIQUE INDEX "uq_payment_one_success_per_order"
  ON "payment" ("order_id")
  WHERE "status" = 'succeeded';
